# Generated by Django 4.1 on 2022-09-01 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='description',
            field=models.TextField(default='this is the desciption'),
        ),
    ]
